In [2]:
import pandas as pd
from pathlib import Path
# import datetime as dt

In [3]:
# Read the csv files

sept = pd.read_csv("Resources/sept.csv")
oct = pd.read_csv("Resources/oct.csv")
nov = pd.read_csv("Resources/nov.csv")
dec = pd.read_csv("Resources/dec.csv")

# Display  dec dataframe 
dec.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,28A17ACD224CD80B,electric_bike,2024-12-06 17:50:49.428,2024-12-06 17:54:20.070,Oakland Ave,JC022,Hilltop,JC019,40.737604,-74.052478,40.731169,-74.057574,member
1,3508393A86FBD357,classic_bike,2024-12-14 11:01:00.309,2024-12-14 11:12:01.382,Oakland Ave,JC022,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.737604,-74.052478,40.735938,-74.030305,member
2,75FA4C03A1447401,electric_bike,2024-12-24 08:07:17.475,2024-12-24 08:14:14.612,Oakland Ave,JC022,Leonard Gordon Park,JC080,40.737604,-74.052478,40.745910,-74.057271,member
3,C7741EF495C597DD,classic_bike,2024-12-19 12:48:05.452,2024-12-19 12:54:15.253,Oakland Ave,JC022,Leonard Gordon Park,JC080,40.737604,-74.052478,40.745910,-74.057271,member
4,07952BB20B46C5B1,electric_bike,2024-12-17 11:19:37.631,2024-12-17 11:28:25.150,Oakland Ave,JC022,Grove St PATH,JC115,40.737604,-74.052478,40.719410,-74.043090,casual

In [4]:
# Concat july to dec dataframes
combined_df = pd.concat([sept, oct, nov, dec], ignore_index=True)
combined_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C10DA8247151C689,electric_bike,2024-09-01 18:31:52.133,2024-09-01 19:03:37.824,Oakland Ave,JC022,Oakland Ave,JC022,40.737604,-74.052478,40.737604,-74.052478,casual
1,CA8F467FAE5F5607,electric_bike,2024-09-17 18:48:42.751,2024-09-17 18:53:29.210,Oakland Ave,JC022,Hoboken Ave at Monmouth St,JC105,40.737604,-74.052478,40.735208,-74.046964,member
2,72FFCD5D931EA4A7,electric_bike,2024-09-18 08:43:20.749,2024-09-18 08:48:55.307,Oakland Ave,JC022,Hilltop,JC019,40.737604,-74.052478,40.731169,-74.057574,member
3,B50000CFD3A1F27C,electric_bike,2024-09-25 07:50:55.028,2024-09-25 07:57:20.498,Oakland Ave,JC022,Madison St & 1 St,HB402,40.737604,-74.052478,40.738790,-74.039300,member
4,6CBE8DAA923538C4,electric_bike,2024-09-07 11:15:55.595,2024-09-07 11:25:40.109,Oakland Ave,JC022,Hamilton Park,JC009,40.737604,-74.052478,40.727596,-74.044247,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
373987,7E81F3435D05D1F4,electric_bike,2024-12-28 09:45:30.704,2024-12-28 09:48:02.706,Marin Light Rail,JC013,Exchange Pl,JC116,40.714584,-74.042817,40.716366,-74.034344,member
373988,70499242367CEA82,classic_bike,2024-12-12 16:21:50.427,2024-12-12 16:26:34.069,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member
373989,146BB7BEE3C31DAC,classic_bike,2024-12-11 19:23:24.109,2024-12-11 19:25:07.612,Grove St PATH,JC115,Manila & 1st,JC082,40.719410,-74.043090,40.721651,-74.042884,member
373990,ADA14EC995D83769,classic_bike,2024-12-12 20:48:40.471,2024-12-12 20:52:41.722,Grove St PATH,JC115,Exchange Pl,JC116,40.719410,-74.043090,40.716366,-74.034344,member
373991,214E88D0B0FCBA75,classic_bike,2024-12-04 18:14:12.686,2024-12-04 18:19:02.621,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member

In [5]:
# Create a copy of combined_df
df = combined_df.copy()

In [6]:
# Convert started_at and ended_at to date time datatype
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

In [7]:
# Drop rows with missing values
df1 = df.dropna(how='any')
df1

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C10DA8247151C689,electric_bike,2024-09-01 18:31:52.133,2024-09-01 19:03:37.824,Oakland Ave,JC022,Oakland Ave,JC022,40.737604,-74.052478,40.737604,-74.052478,casual
1,CA8F467FAE5F5607,electric_bike,2024-09-17 18:48:42.751,2024-09-17 18:53:29.210,Oakland Ave,JC022,Hoboken Ave at Monmouth St,JC105,40.737604,-74.052478,40.735208,-74.046964,member
2,72FFCD5D931EA4A7,electric_bike,2024-09-18 08:43:20.749,2024-09-18 08:48:55.307,Oakland Ave,JC022,Hilltop,JC019,40.737604,-74.052478,40.731169,-74.057574,member
3,B50000CFD3A1F27C,electric_bike,2024-09-25 07:50:55.028,2024-09-25 07:57:20.498,Oakland Ave,JC022,Madison St & 1 St,HB402,40.737604,-74.052478,40.738790,-74.039300,member
4,6CBE8DAA923538C4,electric_bike,2024-09-07 11:15:55.595,2024-09-07 11:25:40.109,Oakland Ave,JC022,Hamilton Park,JC009,40.737604,-74.052478,40.727596,-74.044247,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
373987,7E81F3435D05D1F4,electric_bike,2024-12-28 09:45:30.704,2024-12-28 09:48:02.706,Marin Light Rail,JC013,Exchange Pl,JC116,40.714584,-74.042817,40.716366,-74.034344,member
373988,70499242367CEA82,classic_bike,2024-12-12 16:21:50.427,2024-12-12 16:26:34.069,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member
373989,146BB7BEE3C31DAC,classic_bike,2024-12-11 19:23:24.109,2024-12-11 19:25:07.612,Grove St PATH,JC115,Manila & 1st,JC082,40.719410,-74.043090,40.721651,-74.042884,member
373990,ADA14EC995D83769,classic_bike,2024-12-12 20:48:40.471,2024-12-12 20:52:41.722,Grove St PATH,JC115,Exchange Pl,JC116,40.719410,-74.043090,40.716366,-74.034344,member
373991,214E88D0B0FCBA75,classic_bike,2024-12-04 18:14:12.686,2024-12-04 18:19:02.621,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member

In [8]:
# New dataframe where date is more or equal to '2024-07-01" and less than equal to '2024-12-31'
df2 = df1[(df1['started_at'] >= "2024-09-01") & (df1['ended_at']<= '2024-12-31')]
df2

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C10DA8247151C689,electric_bike,2024-09-01 18:31:52.133,2024-09-01 19:03:37.824,Oakland Ave,JC022,Oakland Ave,JC022,40.737604,-74.052478,40.737604,-74.052478,casual
1,CA8F467FAE5F5607,electric_bike,2024-09-17 18:48:42.751,2024-09-17 18:53:29.210,Oakland Ave,JC022,Hoboken Ave at Monmouth St,JC105,40.737604,-74.052478,40.735208,-74.046964,member
2,72FFCD5D931EA4A7,electric_bike,2024-09-18 08:43:20.749,2024-09-18 08:48:55.307,Oakland Ave,JC022,Hilltop,JC019,40.737604,-74.052478,40.731169,-74.057574,member
3,B50000CFD3A1F27C,electric_bike,2024-09-25 07:50:55.028,2024-09-25 07:57:20.498,Oakland Ave,JC022,Madison St & 1 St,HB402,40.737604,-74.052478,40.738790,-74.039300,member
4,6CBE8DAA923538C4,electric_bike,2024-09-07 11:15:55.595,2024-09-07 11:25:40.109,Oakland Ave,JC022,Hamilton Park,JC009,40.737604,-74.052478,40.727596,-74.044247,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
373987,7E81F3435D05D1F4,electric_bike,2024-12-28 09:45:30.704,2024-12-28 09:48:02.706,Marin Light Rail,JC013,Exchange Pl,JC116,40.714584,-74.042817,40.716366,-74.034344,member
373988,70499242367CEA82,classic_bike,2024-12-12 16:21:50.427,2024-12-12 16:26:34.069,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member
373989,146BB7BEE3C31DAC,classic_bike,2024-12-11 19:23:24.109,2024-12-11 19:25:07.612,Grove St PATH,JC115,Manila & 1st,JC082,40.719410,-74.043090,40.721651,-74.042884,member
373990,ADA14EC995D83769,classic_bike,2024-12-12 20:48:40.471,2024-12-12 20:52:41.722,Grove St PATH,JC115,Exchange Pl,JC116,40.719410,-74.043090,40.716366,-74.034344,member
373991,214E88D0B0FCBA75,classic_bike,2024-12-04 18:14:12.686,2024-12-04 18:19:02.621,Marin Light Rail,JC013,Manila & 1st,JC082,40.714584,-74.042817,40.721651,-74.042884,member

In [10]:
# Save to csv
df2.to_csv("clean_data/data_0712.csv", index=False)